# Generated by Django 4.0.5 on 2022-06-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, verbose_name='Creado')),
                ('instrument', models.SmallIntegerField(choices=[(1, 'Cliente'), (1, 'Cuenta'), (3, 'Inversion'), (4, 'Credito')])),
                ('instrument_id', models.IntegerField(verbose_name='InstrumentoID')),
                ('client_id', models.IntegerField(verbose_name='ClienteID')),
                ('status', models.CharField(choices=[('R', 'Registrado'), ('P', 'Procesado'), ('E', 'Error')], max_length=10, verbose_name='Status')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='LogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel', models.IntegerField(choices=[(1, 'SAFI_LIB'), (2, 'SAFI_REST'), (3, 'SYGLOBAL_REST')], verbose_name='Canal')),
                ('type', models.CharField(choices=[('in', 'Consulta'), ('out', 'Envio')], max_length=5, verbose_name='Tipo')),
                ('request', models.TextField(max_length=3000, verbose_name='Peticion')),
                ('response', models.TextField(verbose_name='Respuesta')),
                ('send_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Envio')),
                ('Queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.queue')),
            ],
        ),
    ]
